# Generated by Django 5.1.5 on 2025-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('number', models.PositiveBigIntegerField(unique=True, verbose_name='Номер стола')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['number'],
            },
        ),
    ]
