# Generated by Django 5.1.5 on 2025-02-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                (
                    'total_price',
                    models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')],
                        default='pending',
                        max_length=10,
                        verbose_name='Статус заказа',
                    ),
                ),
                (
                    'table_number',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='Стол'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                (
                    'dish',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='order_items',
                        to='dishes.dish',
                        verbose_name='Блюдо',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='order_items',
                        to='orders.order',
                        verbose_name='Заказ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='orders.OrderItem', to='dishes.dish', verbose_name='Заказанные блюда'),
        ),
    ]
